#!/usr/bin/env bash

if
  [[ -s "/home/nitrous/code/labs/first-lab-ruby-learn-cli-nitrous-intro-to-learn/.bundle/environment" ]]
then
  source "/home/nitrous/code/labs/first-lab-ruby-learn-cli-nitrous-intro-to-learn/.bundle/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/nitrous/code/labs/first-lab-ruby-learn-cli-nitrous-intro-to-learn/.bundle/environment'" >&2
  exit 1
fi
